package app;
import classes.*;

public class AgendaGUI extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    
    public AgendaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoForm = new javax.swing.JComboBox();
        emailForm = new javax.swing.JTextField();
        codeForm = new javax.swing.JTextField();
        foneForm = new javax.swing.JTextField();
        nomeForm = new javax.swing.JTextField();
        addContato = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listContato = new javax.swing.JList();
        rmvContato = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda");
        setBackground(new java.awt.Color(154, 154, 176));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.darkGray);
        setLocation(new java.awt.Point(300, 233));
        setName("mainFrame"); // NOI18N
        setResizable(false);

        tipoForm.setMaximumRowCount(2);
        tipoForm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Física", "Jurídica" }));
        tipoForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoFormActionPerformed(evt);
            }
        });

        emailForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFormActionPerformed(evt);
            }
        });

        foneForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foneFormActionPerformed(evt);
            }
        });

        nomeForm.setBackground(new java.awt.Color(174, 178, 199));
        nomeForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFormActionPerformed(evt);
            }
        });

        addContato.setText("Adicionar");
        addContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addContatoActionPerformed(evt);
            }
        });

        listContato.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listContato);

        rmvContato.setText("Remove");
        rmvContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmvContatoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Telefone");

        jLabel3.setText("E-mail");

        jLabel4.setText("CPF/CNPJ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailForm, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                            .addComponent(foneForm)
                            .addComponent(codeForm, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeForm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addContato, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tipoForm, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rmvContato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tipoForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeForm, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeForm, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foneForm, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailForm, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rmvContato)
                    .addComponent(addContato))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addContatoActionPerformed
        int tipo = this.tipoForm.getSelectedIndex();
        String cpf = this.codeForm.getText();
        String email = this.emailForm.getText();
        String foneS = this.foneForm.getText();
        int fone = Integer.parseInt(foneS);
        String nome = this.nomeForm.getText();
        Contatos contatosf = new Contatos();
        contatosf.setContact(fone,email);
        Pessoa pessoaf = new Fisica(nome, contatosf, cpf, tipo);
        contatosf.addContato(pessoaf);
        contatosf.toString();
    }//GEN-LAST:event_addContatoActionPerformed

    private void rmvContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmvContatoActionPerformed
        
    }//GEN-LAST:event_rmvContatoActionPerformed

    private void emailFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFormActionPerformed
        
    }//GEN-LAST:event_emailFormActionPerformed

    private void foneFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foneFormActionPerformed
        
    }//GEN-LAST:event_foneFormActionPerformed

    private void nomeFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFormActionPerformed
        
    }//GEN-LAST:event_nomeFormActionPerformed

    private void tipoFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoFormActionPerformed
        
    }//GEN-LAST:event_tipoFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        int tipo = 0;
        String nome = "0";
        int fone = 0;
        String email = "0";
        String cpf = "0";
        String cnpj = "0";

        switch(tipo){

            case 1:
                Contatos contatosf = new Contatos();
                contatosf.setContact(fone,email);
                Pessoa pessoaf = new Fisica(nome, contatosf, cpf, tipo);
                contatosf.addContato(pessoaf);
                contatosf.toString();
                break;

            case 2: 
                Contatos contatosj = new Contatos();
                contatosj.setContact(fone);
                Pessoa pessoaj = new Juridica(nome, contatosj, cnpj, tipo);
                contatosj.addContato(pessoaj);
                contatosj.toString();
                break;
        }
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addContato;
    private javax.swing.JTextField codeForm;
    private javax.swing.JTextField emailForm;
    private javax.swing.JTextField foneForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listContato;
    private javax.swing.JTextField nomeForm;
    private javax.swing.JButton rmvContato;
    private javax.swing.JComboBox tipoForm;
    // End of variables declaration//GEN-END:variables
}
