package app;
import classes.*;
import javax.swing.table.DefaultTableModel;

public class AgendaGUI<E> extends javax.swing.JFrame {

    Agenda agenda = new Agenda();

    private static final long serialVersionUID = 1L;

    public AgendaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoForm = new javax.swing.JComboBox<E>();
        emailForm = new javax.swing.JTextField();
        codeForm = new javax.swing.JTextField();
        foneForm = new javax.swing.JTextField();
        nomeForm = new javax.swing.JTextField();
        addContato = new javax.swing.JButton();
        rmvContato = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda");
        setBackground(new java.awt.Color(154, 154, 176));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.darkGray);
        setLocation(new java.awt.Point(300, 233));
        setName("mainFrame"); // NOI18N
        setResizable(false);

        tipoForm.setMaximumRowCount(2);
        tipoForm.setModel(new javax.swing.DefaultComboBoxModel<E>((E[]) new String[] { "Física", "Jurídica" }));
        tipoForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoFormActionPerformed(evt);
            }
        });

        emailForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFormActionPerformed(evt);
            }
        });

        codeForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeFormActionPerformed(evt);
            }
        });

        foneForm.setToolTipText("");
        foneForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foneFormActionPerformed(evt);
            }
        });

        nomeForm.setBackground(new java.awt.Color(174, 178, 199));
        nomeForm.setToolTipText("");
        nomeForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFormActionPerformed(evt);
            }
        });

        addContato.setText("Adicionar");
        addContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addContatoActionPerformed(evt);
            }
        });

        rmvContato.setText("Remove");
        rmvContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmvContatoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Telefone");

        jLabel3.setText("E-mail");

        jLabel4.setText("CPF/CNPJ");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Nome", "CPF/CNPJ", "E-Mail", "Fone"
            }
        ) {
            /**
             *
             */
            private static final long serialVersionUID = 1L;
            boolean[] canEdit = new boolean[] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailForm, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                            .addComponent(foneForm)
                            .addComponent(codeForm, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeForm))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addContato, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rmvContato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoForm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tipoForm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeForm, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codeForm, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(foneForm, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailForm, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rmvContato)
                    .addComponent(addContato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addContatoActionPerformed
        
        DefaultTableModel dtb = (DefaultTableModel) jTable1.getModel();
        
        int tipo = this.tipoForm.getSelectedIndex();
        
        String email = this.emailForm.getText();
        String foneS = this.foneForm.getText();
        String nome = this.nomeForm.getText();
        
        this.foneForm.setActionCommand(email);
                
        if(tipo == 0){
            
            String cpf = this.codeForm.getText();
            Contatos contatosf = new Contatos();

            int fone = Integer.parseInt(foneS);
            contatosf.setContact(fone,email);
        
            Pessoa pessoaf = new Fisica(nome, contatosf, cpf, tipo);
            agenda.addContato(pessoaf);
            Object[] cont = {this.tipoForm.getSelectedItem(),nome,cpf,email,fone};
            dtb.addRow(cont);
        }
        else{
            
            String cnpj = this.codeForm.getText();
            Contatos contatosj = new Contatos();
            
            int fone = Integer.parseInt(foneS);
            contatosj.setContact(fone,email);
            
            Pessoa pessoaj = new Juridica(nome, contatosj, cnpj, tipo);
            agenda.addContato(pessoaj);
            Object[] cont = {this.tipoForm.getSelectedItem(),nome,cnpj,email,fone};
            dtb.addRow(cont);
        }
        System.out.println(agenda.toString());
            
    }//GEN-LAST:event_addContatoActionPerformed

    private void rmvContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmvContatoActionPerformed

    }//GEN-LAST:event_rmvContatoActionPerformed

    private void emailFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFormActionPerformed
        
    }//GEN-LAST:event_emailFormActionPerformed

    private void foneFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foneFormActionPerformed
        
    }//GEN-LAST:event_foneFormActionPerformed

    private void nomeFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFormActionPerformed
        
    }//GEN-LAST:event_nomeFormActionPerformed

    private void tipoFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoFormActionPerformed
        
    }//GEN-LAST:event_tipoFormActionPerformed

    private void codeFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeFormActionPerformed
        
    }//GEN-LAST:event_codeFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        Agenda agenda = new Agenda();

        int tipo = 0;
        String nome = "0";
        int fone = 0;
        String email = "0";
        String cpf = "0";
        String cnpj = "0";

        switch(tipo){

            case 0:
                Contatos contatosf = new Contatos();
                contatosf.setContact(fone,email);
                Pessoa pessoaf = new Fisica(nome, contatosf, cpf, tipo);
                agenda.addContato(pessoaf);
                System.out.println(agenda.toString());
                break;

            case 1: 
                Contatos contatosj = new Contatos();
                contatosj.setContact(fone);
                Pessoa pessoaj = new Juridica(nome, contatosj, cnpj, tipo);
                agenda.addContato(pessoaj);
                System.out.println(agenda.toString());
                break;
        }
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        // Create and display the form
        java.awt.EventQueue.invokeLater(() -> {
            new AgendaGUI().setVisible(true);
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addContato;
    private javax.swing.JTextField codeForm;
    private javax.swing.JTextField emailForm;
    private javax.swing.JTextField foneForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nomeForm;
    private javax.swing.JButton rmvContato;
    private javax.swing.JComboBox<E> tipoForm;
    // End of variables declaration//GEN-END:variables
}
